### ISSUE TITLE
Observable.value thread safe

### ISSUE THREAD

**Issue by 4brunu** [roberthein/Observable#11]
One thing that worries me, is that Observable.value is not thread safe.

What do you think about adding some thread safe mechanism, like atomic, to ensure that Observable.value doesn't get changed by two thread at same time?

**Comment by roberthein** [comment]
Yeah, you're right. Sounds good. Do you know how to go about this?

**Comment by 4brunu** [comment]
Actually no... 😅 And you?
I think atomic would be a good choice for this, but Swift doesn't have Atomic properties, so we need to implement an Atomic Wrapper like [this](https://stackoverflow.com/questions/30851339/how-do-i-atomically-increment-a-variable-in-swift/42156140) or [this](http://www.vadimbulavin.com/atomic-properties/).
Do you want to give it a try, or should I? 🙂

**Comment by roberthein** [comment]
I don't have time for this right now, but could pick it up later.. What you want.
