### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by 4brunu** [roberthein/Observable#13]
I opened this issue, to continue the conversation started in https://github.com/roberthein/Observable/pull/12 about tests.

Do you want create the Xcode project to add the test target, or should I create it? 🙂

**Comment by roberthein** [comment]
If you wouldn't mind. 🙂
Btw, I just release Observable 1.4.0 with all your previous PR's. Thank you so much for all your contributions so far! 🙏

**Comment by 4brunu** [comment]
Thanks for being so open to external contributions 👍 
By the way, could you please also release 1.4.0 on Cocoapods? 
Thanks

**Comment by roberthein** [comment]
I already did, this afternoon.. maybe run `pod update`?

**Comment by 4brunu** [comment]
You are right 🙂 The search at Cocoapods.org shows version 1.3.3, but the Podspec file of 1.4.0 is already published. Thanks 👍

**Comment by roberthein** [comment]
Thank you @Edudjr and @4brunu, I just published Observable (2.0.0) successfully. 🙏
