### ISSUE TITLE
Carthage installation instructions from readme don't work

### ISSUE THREAD

**Issue by jameszaghini** [roberthein/Observable#17]
I added Observable to my Cartfile as per the readme
```github "roberthein/Observable" "master"```

But it didn't work:
> *** Cloning Observable
> *** Checking out Observable at "513781328be8ed6b66ab71c4ea2a59b736140f41"
> *** xcodebuild output can be found in /var/folders/l0/hwn7fkf57_b1sxlp360mg3lr0000gn/T/carthage-xcodebuild.NPMhHh.log
> 
> *** Skipped building Observable due to the error:
> Dependency "Observable" has no shared framework schemes
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/roberthein/Observable/issues/new

**Comment by sanderrouk** [comment]
👍

**Comment by roberthein** [comment]
You are right Carthage is not yet supported.. I'll remove it from the readme for now.
