### ISSUE TITLE
Deadlock when updating observable value from within observation

### ISSUE THREAD

**Issue by lm2s** [roberthein/Observable#19]
I've just noticed that updating the value of an observable from within an observation results in deadlock because a mutex is being used to ensure thread safety. The mutex could be replaced by DispatchQueues and avoid this issue.
Is there a specific reason as to why mutexes are being used instead of DispatchQueues?

I can do a PR for this.

**Comment by roberthein** [comment]
🤔 Good point! I'm looking forward to your PR :)

**Comment by lm2s** [comment]
Created PR #20 :) I've been testing it and everything seems to be working properly.

**Comment by roberthein** [comment]
Works great @lm2s, so I merged it. Thank you so much for this contribution. 🙏

**Comment by lm2s** [comment]
@roberthein glad to contribute 🙂
