### ISSUE TITLE
Make Observable and ImmutableObservable 'open' classes

### ISSUE THREAD

**Issue by alsidor** [roberthein/Observable#27]
Hi! Thanks for the nice library.

Could you change Observable and ImmutableObservable classes to be 'open'
It will allow creating some project specific Observables classes.
E.g. I want to implement ProgressObservable which should extend from ImmutableObservable<Bool>

**Comment by 4brunu** [comment]
This lib now used PropertyWrappers, and they can't be open because of a Swift bug.
Here is the PR that will fix this in Swift https://github.com/apple/swift/pull/29023.
When a version of Swift is available with this fix, the `Observable` and `MutableObservable` classes can be made open.

**Comment by roberthein** [comment]
I'll also keep an eye on this.

**Comment by 4brunu** [comment]
With Swift 5.2 this is now possible, so I opened https://github.com/roberthein/Observable/pull/50
