### ISSUE TITLE
[Feature] Adding helper methods .bind()

### ISSUE THREAD

**Issue by bfrolicher** [roberthein/Observable#44]
Hello,

Firstly a big thanks for this library !
I'm using Observable in a lot of projects and I love it. It fit really well with mvvm.
But if you have a lot of properties, the viewController get fat. 
1 observable is about 3 lines of codes, so 10 observables is 30 lines. Readability and maintainability become less clear.

The idea is to reduce the number of line of code to juste one, for all simple cases.

What do you think about adding something like that :

```swift 
func bind<O: NSObject>(to object: O, _ objectKeyPath: ReferenceWritableKeyPath<O, T>, disposal: inout Disposal)
or
func bind<O: NSObject, R>(to object: O, _ objectKeyPath: ReferenceWritableKeyPath<O, R>, disposal: inout Disposal, transform: @escaping (T) -> R)

```
usage:  

```swift 
class ViewModel {
   @observable var firstname: String 
}

class ViewController {

    @IBOutlet private weak var firstnameTextField: UITextField!

    func viewDidLoad() {
        viewModel.firstname.bind(to: self.firstnameTextField, \.text, disposal: &self.disposal)
        // or 
        viewModel.firstname.bind(to: self.firstnameTextField, \.text, disposal: &self.disposal) {
              v?.uppercased()
        }

    }
}
```

I have make some tests with simple cases and it's seems to works, but I'm sure that more work is needed to fit complexes cases and generic makes me sick.

if this proposal fits with the spirit of Observable, I can make a PR. (if not I keep that in an extension 😉 )

**Comment by 4brunu** [comment]
Looks good to me 👍 
@roberthein what do you think about this?

**Comment by 4brunu** [comment]
Since this was merged, maybe we can now close this issue.
@bfrolicher what do you think?

**Comment by bfrolicher** [comment]
@4brunu 
Sure, we can close it. ;-)
