### ISSUE TITLE
Library life 

### ISSUE THREAD

**Issue by bfrolicher** [roberthein/Observable#48]
Hi,

Two months have passed since my last comments and still no answer. 
I love this library but we (developers) need to be sure that the tools we use are maintained and that there is a semblance of life. 
This is not a criticism, I know it's not always easy to spend time on it, but I need an answer.
What is the future of this library ? 
Should I make a fork, and move on my own or move on to something else?

Sincerely 
Benjamin

**Comment by roberthein** [comment]
Hey @bfrolicher you're absolutely right and yes it is hard sometimes to keep all the balls in the air. 😁 But I Do like your `Add bind helper` pr and will merge it later today. Sorry for the delay. ✌️

**Comment by roberthein** [comment]
Ey @bfrolicher(and @4brunu) sorry again for the delay on this, but I just pushed 2.1.0 with your binding extension.
Thank you for this great addition. 🙏
