### ISSUE TITLE
Observe on a given DispatchQueue 

### ISSUE THREAD

**Issue by 4brunu** [roberthein/Observable#6]
Hi, first thanks for this awesome library!

It would be great if it would be possible to add an observer on a given DispatchQueue.

```
position.observe(DispatchQueue.main) { p in
    // handle new position
}
```

To make this  change without breaking the API, the DispatchQueue could be an optional parameter.

What do you think of this?
If you agreed with this change, I can try to make a PR if you want 🙂

**Comment by roberthein** [comment]
Thank you @4brunu!
I think that would be an awesome addition indeed. 😍

**Comment by 4brunu** [comment]
Should I create a PR, or do you prefeer to do it? 🙂

**Comment by roberthein** [comment]
It's your idea, so go ahead.. I'll do my best to merge it asap. 🙏
