### ISSUE TITLE
Observable with readonly value

### ISSUE THREAD

**Issue by 4brunu** [roberthein/Observable#7]
Hey, I would like to have the ability of having an Observable with readonly value.

This way we can make sure that some classes that are should only observe changes, don't emit values.

What do you think?

**Comment by roberthein** [comment]
Interesting @4brunu.. 🤔
Never needed this before but I can imagine plenty of use cases for it.
Are you making another PR? 😅

**Comment by 4brunu** [comment]
Yes, just wanted to validate the idea with you, before start coding 😄
